import {
  AlertCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ClockIcon,
  DotIcon,
  FileEditIcon,
  HomeIcon,
  Loader2Icon,
  MoonIcon,
  MoreHorizontalIcon,
  PackagePlusIcon,
  PencilIcon,
  PlusIcon,
  SearchIcon,
  ShoppingBasketIcon,
  SunIcon,
  TrashIcon,
  TruckIcon,
  UserIcon,
  XIcon,
  type LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icon = {
  sun: SunIcon,
  moon: MoonIcon,
  search: SearchIcon,
  loading: Loader2Icon,
  edit: FileEditIcon,
  delete: TrashIcon,
  checkmark: CheckIcon,
  home: HomeIcon,
  x: XIcon,
  pencil: PencilIcon,
  plus: PlusIcon,
  addProduct: PackagePlusIcon,
  dot: DotIcon,
  more: MoreHorizontalIcon,
  alert: AlertCircleIcon,
  chevronRight: ChevronRightIcon,
  chevronLeft: ChevronLeftIcon,
  chevronDown: ChevronDownIcon,
  user: UserIcon,
  cart: ShoppingBasketIcon,
  clock: ClockIcon,
  truck: TruckIcon,
};
